# site settings
title: Malav Bateriwala
subtitle: Website
email: malav.b93@gmail.com
description: Robotics and Machine learning engineer who wants a pet panda.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bigmb.github.io"
author: Malav Bateriwala
street_address: Bowen Street
city: Brisbane
state: Queensland
zip_code: 4006
country: Australia
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# social settings
500px_url:
facebook_url: https://www.facebook.com/MR.bigmb
github_url: https://github.com/bigmb
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/malav_mb/
linkedin_url: https://www.linkedin.com/in/malav-bateriwala/
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
